CONFIG_ZMK_POINTING=y

CONFIG_I2C=y
CONFIG_INPUT_TPS43=y
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_BATTERY_REPORTING=y

# Enter normal idle after 30 seconds and deep sleep after 60 minutes.
# See https://zmk.dev/docs/features/low-power-states
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

CONFIG_INPUT_THREAD_STACK_SIZE=2048
